<div class='s6v_<?php echo $this->application()->Settings()->wpslug ?>'>
<form action="" method="post">
<input type='hidden' name='roles[]' value = ''>
<table class="widefat post fixed" cellspacing="0">
	<thead> 
		<tr>
			<th style='width:150px'>Role</th>
			<th>Export</th>
		</tr>
	</thead>
	<tbody>
	<?php foreach($this->settings['roles'] as $key=>$value):?>
		<tr class='<?php echo $this->alternate()?>'>
			<td><?php echo $key?></td>
			<td><input type='checkbox' name='roles[<?php echo $key?>]' value = 'checked' <?php echo $value?> /></td>
		</tr>
	<?php endforeach;?>
	</tbody>
</table>
<br/>
<table class="widefat post fixed" cellspacing="0">
	<thead> 
		<tr>
			<th style='width:150px'>Extra Settings</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<tr class='<?php echo $this->alternate()?>'>
			<td colspan = 2>A commenter must have at least <input type=text name='comment_count' value='<?php echo $this->settings['comment_count']?>' size=2 /> approved comments to be included.</td>
		</tr>
	</tbody>
</table>
<br/>
<input type='submit' class='button' value='Apply' />&nbsp;<a href='<?php echo $this->download_url?>'>Download</a>
<br/>
<br/>
<table class="widefat post fixed" cellspacing="0">
	<thead> 
		<tr>
			<th class="quick_help" >Quick Help</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
	<tr class='<?php echo $this->alternate();?>'>
		<th>Export</th>
		<td>Check the roles you want to be included in the download file.
		</td>
	</tr>
	<tr class='<?php echo $this->alternate();?>'>
		<th>Role</th>
		<td>Role corresponds to WordPress roles with the exception of 'Commenter' which are readers who are not Users but who have commented and meet the minimum number of comments.</td>
	</tr>
	<tr class='<?php echo $this->alternate();?>'>
		<th>download</th>
		<td>You must apply the new settings before downloading.
		</td>
	</tr>
	<tr class='<?php echo $this->alternate();?>'>
		<th>Exported Fields</th>
		<td>The following fields will be exported for each user: 'name','email','url','date','role'.
		</td>
	</tr>
	<tr class='<?php echo $this->alternate();?>'>
		<th>Date</th>
		<td>For WordPress users the 'date' will be their registration date, for commenters it will be the date of there first approved comment.</td>
	</tr>
 	<tr class='<?php echo $this->alternate();?>'>
		<th>Security</th>
		<td>No files are stored on the server, URL rewriting is used to create the download file on the fly. Only administrators can download this file.</td>
	</tr>
 	</tbody>
</table>
</form>
</div>

